### ISSUE TITLE
ld: warning: Could not find auto-linked framework 'MMKV'

### ISSUE THREAD

**Issue by jordanmkoncz** [FidMe/react-native-fast-storage#2]
I've been trying to set up this library for my project and found that `react-native link react-native-fast-storage` appears to link dependencies incorrectly. After adding `react-native-fast-storage` and running the `react-native link` command, when I try to create a build or run the app (i.e. `react-native run-ios`), I get the following error:

```
ld: warning: Could not find auto-linked framework 'MMKV'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MMKV", referenced from:
      objc-class-ref in libRNFastStorage.a(RNFastStorage.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

After some trial and error I seem to have found a way to manually finish linking `react-native-fast-storage` correctly. I had to do the following:

1. In Xcode, select the project, then select the main target (under "Targets"), then go to the "Build Settings" tab, and find the "Framework Search Paths" section. Add `../node_modules/react-native-fast-storage/ios` (non-recursive) for each of your configurations (e.g. Debug and Release).
2. Find the `MMKV.framework` file in `../node_modules/react-native-fast-storage/ios` and drag it into Xcode under the "Frameworks" section. In the dialog that pops up, uncheck "Copy items if needed", choose "Create groups", and ensure your main target is checked under "Add to targets".
3. In Xcode, select the project, then select the main target (under "Targets"), then go to the "General" tab and find the "Embedded Binaries" section. Click the "+" icon and select `MMKV.framework` which appears under "Frameworks" then click "Add".
4. In Xcode do "Product" -> "Clean".

After performing these steps I was able to successfully build/run the project and `react-native-fast-storage` appears to be working correctly (I'm using it as my storage engine for `redux-persist`).

So it seems to me like the `react-native link react-native-fast-storage` step is not currently performing all the necessary steps right now. Hopefully this library can be updated so that it does all the necessary steps automatically.

My environment:
```
{
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-fast-storage": "0.0.1",
}
```

**Comment by Michaelvilleneuve** [comment]
I've had the same issue the first time I linked it, I needed to add the same steps as you did. 
It disappeared after a few tried so I thought I fixed it but it may have been some cache left. 

I will update the README, thank you for reporting this !
